# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fb6e2bc8-6235-447a-9aca-87f53fa9e29a";
      fsType = "btrfs";
      options = [ "compress=zstd,subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fb6e2bc8-6235-447a-9aca-87f53fa9e29a";
      fsType = "btrfs";
      options = [ "compress=zstd,subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/fb6e2bc8-6235-447a-9aca-87f53fa9e29a";
      fsType = "btrfs";
      options = [ "compress=zstd,noatime,subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9edb42ed-18ce-401d-b37e-afad46763122"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
