
editor = 'nvim'
cursor = '▇'
blinking-cursor = false
use-kitty-keyboard-protocol = true
performance = "High"
theme = "GruvboxDarkHard"

[window]
width = 600
height = 400
mode = "Windowed"
foreground-opacity = 1.0
background-opacity = 0.6
blur = true

[fonts]
family = "Lilex Nerd Font"
size = 18

[fonts.regular]
family = "Lilex Nerd Font"
style = "Regular"
weight = 400

[fonts.bold]
family = "Lilex Nerd Font"
style = "Bold"
weight = 800

[fonts.italic]
family = "Lilex Nerd Font"
style = "Italic"
weight = 400

[fonts.bold-italic]
family = "Lilex Nerd Font"
style = "Bold-Italic"
weight = 800

# GruvboxDarkHard.toml
# https://github.com/raphamorim/rio-terminal-themes/blob/main/themes/GruvboxDarkHard.toml
[colors]
background = '#1b1b1b'
foreground = '#ebdbb2'
selection-background = '#665c54'
selection-foreground = '#ebdbb2'
cursor = '#ebdbb2'
black = '#1b1b1b'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'
light_black = '#928374'
light_red = '#fb4934'
light_green = '#b8bb26'
light_yellow = '#fabd2f'
light_blue = '#83a598'
light_magenta = '#d3869b'
light_cyan = '#8ec07c'
light_white = '#ebdbb2'

[navigation]
mode = "CollapsedTab"
clickable = true
use-current-path = false
color-automation = []

shell = { program = "/bin/zsh", args = ["--login"] }
working-dir = "/home/$USER/"
disable-renderer-when-unfocused = false
use-fork = false

